[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
buildEnvironment = "V3"

[deploy]
runtime = "V2"
numReplicas = 1
healthcheckPath = "/"
sleepApplication = false
useLegacyStacker = false
ipv6EgressEnabled = false
[[deploy.multiRegionConfig]]&#10;[asia-southeast1-eqsg3a]&#10;numReplicas = 1
restartPolicyType = "ON_FAILURE"
healthcheckTimeout = 60
startupTimeout = 300
restartPolicyMaxRetries = 10

